### ISSUE TITLE
Image to latent space

### ISSUE THREAD

**Issue by florian-hoenicke** [HackerPoet/FaceEditor#1]
Hi, I would like to contribute to your Project - it is really nice!
One question: How would I adjust your GitHub project to also convert Faces into the Latentspace?
Then we could load a picture into the editor as well.

**Comment by HackerPoet** [comment]
There's a couple options:

One way is to simply use an auto-encoder rather than an embedding layer as the encoder part.  I've tried it and it works about as well as the embedding, but it's twice as slow to train since you need the encoder and decoder in the network.

The other option is to just make another CNN that learns to directly map the faces to the latent space after the embedding was already trained.  This means you don't have to retrain the generator side, but I don't know how accurate that mapping would be...

**Comment by florian-hoenicke** [comment]
Thanks a lot for your response.
This is really interesting. I will try to implement the autoencoder as well.
Your data generator creates noisy images and stores it in x_data. Why were you creating these pictures? Has it something to do with the autoencoder you implemented before?
Greetings Florian

**Comment by HackerPoet** [comment]
I'm not sure if I understand the question, but no, an autoencoder is not required.  The latent space is only noisy during initialization.  Once the network starts training, those vectors start moving to their optimal locations in the latent space (that's what the embedding layer does).

**Comment by florian-hoenicke** [comment]
There is a file named "datagen.py" which creates a file "x_data.npy".
x_data.npy contains the detected edges of the training images. 
I was wondering why this is created, since it is not used by the encoder.py.

**Comment by HackerPoet** [comment]
Oh sorry.  'x_data' is actually used for [DeepDoodle](https://github.com/HackerPoet/DeepDoodle) since both projects share that file "datagen.py".  You can ignore it for this project, its not used.  If you want to try an auto-encoder, the input and output are both y_train.
